//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace CompanyModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ChatEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ChatEntities object using the connection string found in the 'ChatEntities' section of the application configuration file.
        /// </summary>
        public ChatEntities() : base("name=ChatEntities", "ChatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ChatEntities object.
        /// </summary>
        public ChatEntities(string connectionString) : base(connectionString, "ChatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ChatEntities object.
        /// </summary>
        public ChatEntities(EntityConnection connection) : base(connection, "ChatEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<AdminUser> AdminUsers
        {
            get
            {
                if ((_AdminUsers == null))
                {
                    _AdminUsers = base.CreateObjectSet<AdminUser>("AdminUsers");
                }
                return _AdminUsers;
            }
        }
        private ObjectSet<AdminUser> _AdminUsers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Chat> Chats
        {
            get
            {
                if ((_Chats == null))
                {
                    _Chats = base.CreateObjectSet<Chat>("Chats");
                }
                return _Chats;
            }
        }
        private ObjectSet<Chat> _Chats;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Client> Clients
        {
            get
            {
                if ((_Clients == null))
                {
                    _Clients = base.CreateObjectSet<Client>("Clients");
                }
                return _Clients;
            }
        }
        private ObjectSet<Client> _Clients;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the AdminUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToAdminUsers(AdminUser adminUser)
        {
            base.AddObject("AdminUsers", adminUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Chats EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToChats(Chat chat)
        {
            base.AddObject("Chats", chat);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClients(Client client)
        {
            base.AddObject("Clients", client);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="emailId">No Metadata Documentation available.</param>
        public int Clear_IsNewToClient(global::System.String emailId)
        {
            ObjectParameter emailIdParameter;
            if (emailId != null)
            {
                emailIdParameter = new ObjectParameter("EmailId", emailId);
            }
            else
            {
                emailIdParameter = new ObjectParameter("EmailId", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("Clear_IsNewToClient", emailIdParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="emailId">No Metadata Documentation available.</param>
        public int Clear_IsNewToAdmin(global::System.String emailId)
        {
            ObjectParameter emailIdParameter;
            if (emailId != null)
            {
                emailIdParameter = new ObjectParameter("EmailId", emailId);
            }
            else
            {
                emailIdParameter = new ObjectParameter("EmailId", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("Clear_IsNewToAdmin", emailIdParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public int DeleteChatHistory()
        {
            return base.ExecuteFunction("DeleteChatHistory");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<OnlineUserCollection> SP_GetOnlineUsers()
        {
            return base.ExecuteFunction<OnlineUserCollection>("SP_GetOnlineUsers");
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CompanyModel", Name="AdminUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class AdminUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new AdminUser object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="userName">Initial value of the UserName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static AdminUser CreateAdminUser(global::System.Int32 id, global::System.String userName, global::System.String password)
        {
            AdminUser adminUser = new AdminUser();
            adminUser.Id = id;
            adminUser.UserName = userName;
            adminUser.Password = password;
            return adminUser;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserName
        {
            get
            {
                return _UserName;
            }
            set
            {
                OnUserNameChanging(value);
                ReportPropertyChanging("UserName");
                _UserName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserName");
                OnUserNameChanged();
            }
        }
        private global::System.String _UserName;
        partial void OnUserNameChanging(global::System.String value);
        partial void OnUserNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsActive;
        partial void OnIsActiveChanging(Nullable<global::System.Boolean> value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ContactNo
        {
            get
            {
                return _ContactNo;
            }
            set
            {
                OnContactNoChanging(value);
                ReportPropertyChanging("ContactNo");
                _ContactNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ContactNo");
                OnContactNoChanged();
            }
        }
        private global::System.String _ContactNo;
        partial void OnContactNoChanging(global::System.String value);
        partial void OnContactNoChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CompanyModel", Name="Chat")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Chat : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Chat object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="emailID">Initial value of the EmailID property.</param>
        /// <param name="adminID">Initial value of the AdminID property.</param>
        /// <param name="chatString">Initial value of the ChatString property.</param>
        /// <param name="postedOn">Initial value of the PostedOn property.</param>
        public static Chat CreateChat(global::System.Int32 id, global::System.String emailID, global::System.Int32 adminID, global::System.String chatString, global::System.DateTime postedOn)
        {
            Chat chat = new Chat();
            chat.Id = id;
            chat.EmailID = emailID;
            chat.AdminID = adminID;
            chat.ChatString = chatString;
            chat.PostedOn = postedOn;
            return chat;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailID
        {
            get
            {
                return _EmailID;
            }
            set
            {
                OnEmailIDChanging(value);
                ReportPropertyChanging("EmailID");
                _EmailID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailID");
                OnEmailIDChanged();
            }
        }
        private global::System.String _EmailID;
        partial void OnEmailIDChanging(global::System.String value);
        partial void OnEmailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdminID
        {
            get
            {
                return _AdminID;
            }
            set
            {
                OnAdminIDChanging(value);
                ReportPropertyChanging("AdminID");
                _AdminID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AdminID");
                OnAdminIDChanged();
            }
        }
        private global::System.Int32 _AdminID;
        partial void OnAdminIDChanging(global::System.Int32 value);
        partial void OnAdminIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ChatString
        {
            get
            {
                return _ChatString;
            }
            set
            {
                OnChatStringChanging(value);
                ReportPropertyChanging("ChatString");
                _ChatString = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ChatString");
                OnChatStringChanged();
            }
        }
        private global::System.String _ChatString;
        partial void OnChatStringChanging(global::System.String value);
        partial void OnChatStringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PostedOn
        {
            get
            {
                return _PostedOn;
            }
            set
            {
                OnPostedOnChanging(value);
                ReportPropertyChanging("PostedOn");
                _PostedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostedOn");
                OnPostedOnChanged();
            }
        }
        private global::System.DateTime _PostedOn;
        partial void OnPostedOnChanging(global::System.DateTime value);
        partial void OnPostedOnChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsNewToClient
        {
            get
            {
                return _IsNewToClient;
            }
            set
            {
                OnIsNewToClientChanging(value);
                ReportPropertyChanging("IsNewToClient");
                _IsNewToClient = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNewToClient");
                OnIsNewToClientChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsNewToClient;
        partial void OnIsNewToClientChanging(Nullable<global::System.Boolean> value);
        partial void OnIsNewToClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsNewToAdmin
        {
            get
            {
                return _IsNewToAdmin;
            }
            set
            {
                OnIsNewToAdminChanging(value);
                ReportPropertyChanging("IsNewToAdmin");
                _IsNewToAdmin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsNewToAdmin");
                OnIsNewToAdminChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsNewToAdmin;
        partial void OnIsNewToAdminChanging(Nullable<global::System.Boolean> value);
        partial void OnIsNewToAdminChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> PostedForOffline
        {
            get
            {
                return _PostedForOffline;
            }
            set
            {
                OnPostedForOfflineChanging(value);
                ReportPropertyChanging("PostedForOffline");
                _PostedForOffline = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PostedForOffline");
                OnPostedForOfflineChanged();
            }
        }
        private Nullable<global::System.Boolean> _PostedForOffline;
        partial void OnPostedForOfflineChanging(Nullable<global::System.Boolean> value);
        partial void OnPostedForOfflineChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CompanyModel", Name="Client")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Client : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="contactNo">Initial value of the ContactNo property.</param>
        public static Client CreateClient(global::System.String email, global::System.String firstName, global::System.String lastName, global::System.String contactNo)
        {
            Client client = new Client();
            client.Email = email;
            client.FirstName = firstName;
            client.LastName = lastName;
            client.ContactNo = contactNo;
            return client;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                if (_Email != value)
                {
                    OnEmailChanging(value);
                    ReportPropertyChanging("Email");
                    _Email = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Email");
                    OnEmailChanged();
                }
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ContactNo
        {
            get
            {
                return _ContactNo;
            }
            set
            {
                OnContactNoChanging(value);
                ReportPropertyChanging("ContactNo");
                _ContactNo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ContactNo");
                OnContactNoChanged();
            }
        }
        private global::System.String _ContactNo;
        partial void OnContactNoChanging(global::System.String value);
        partial void OnContactNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLoggedIn
        {
            get
            {
                return _LastLoggedIn;
            }
            set
            {
                OnLastLoggedInChanging(value);
                ReportPropertyChanging("LastLoggedIn");
                _LastLoggedIn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoggedIn");
                OnLastLoggedInChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLoggedIn;
        partial void OnLastLoggedInChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoggedInChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> LoggedInWhenOffline
        {
            get
            {
                return _LoggedInWhenOffline;
            }
            set
            {
                OnLoggedInWhenOfflineChanging(value);
                ReportPropertyChanging("LoggedInWhenOffline");
                _LoggedInWhenOffline = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoggedInWhenOffline");
                OnLoggedInWhenOfflineChanged();
            }
        }
        private Nullable<global::System.Boolean> _LoggedInWhenOffline;
        partial void OnLoggedInWhenOfflineChanging(Nullable<global::System.Boolean> value);
        partial void OnLoggedInWhenOfflineChanged();

        #endregion
    
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="CompanyModel", Name="OnlineUserCollection")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class OnlineUserCollection : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OnlineUserCollection object.
        /// </summary>
        /// <param name="email">Initial value of the Email property.</param>
        public static OnlineUserCollection CreateOnlineUserCollection(global::System.String email)
        {
            OnlineUserCollection onlineUserCollection = new OnlineUserCollection();
            onlineUserCollection.Email = email;
            return onlineUserCollection;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();

        #endregion
    }

    #endregion
    
}
